name: Build Installer
run-name: ${{ github.workflow }} ${{ github.event.repository.updated_at}}

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  schedule:
    - cron: "00 00 * * 5"

permissions:
  contents: read

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup UV
        uses: astral-sh/setup-uv@v7.1.6

      - name: Setup Python
        run: uv python install

      - name: Sync Dependencies
        run: uv sync

      - name: Build Executable
        run: uv run build.py -e

      - name: Build Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: setup/setup.iss

      - name: Get Installer Name
        run: |
          $installerName = $(ls .\setup\Output\*.exe).BaseName
          $installerPath = $(ls .\setup\Output\*.exe).FullName

          echo ARTIFACT_NAME=$installerName >> $env:GITHUB_ENV
          echo ARTIFACT_PATH=$installerPath >> $env:GITHUB_ENV

      - name: Create Artifact ${{ env.ARTIFACT_NAME }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
          if-no-files-found: error
